#!/usr/bin/env bash

SRC_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"

install -d /usr/local/bin
install -m 0755 $SRC_DIR/scripts/* /usr/local/bin

install -d /etc/ssh
install -m 644 $SRC_DIR/configs/sshd_config /etc/ssh/sshd_config

systemctl restart sshd

exit 0
